(library (private install sipp)
  (export
    directory-separator-string
    join-string
    replace-source)
  (import (rnrs) (only (chezscheme) directory-separator))
  (define replace-source
    (case-lambda
      [(path) (replace-source path #f)]
      [(path print-sipp-header)
       (with-input-from-file
         path
         (lambda ()
           (when print-sipp-header
             (display ";; DO NOT EDIT THIS FILE!!")
             (newline)
             (display
               ";; This inlined chez-srfi library code is autogenerated using command:")
             (newline)
             (display ";; $ ")
             (display (apply join-string " " (command-line)))
             (newline)
             (display
               ";; Source origin: https://github.com/arcfide/chez-srfi")
             (newline)
             (display
               ";; Please refer to project site for full credits and original code.")
             (newline))
           (display ";;;;;; File header: ")
           (display path)
           (newline)
           (let loop ()
             (case (peek-char)
               [(#\# #\;)
                (display (get-line (current-input-port)))
                (newline)
                (loop)]))
           (let loop ([obj (read)] [acc '()])
             (cond
               [(eof-object? obj) (reverse acc)]
               [else (loop (read) (cons (replace-object obj) acc))]))))]))
  (define replace-object
    (lambda (obj)
      (cond
        [(pair? obj)
         (case (car obj)
           [(include/resolve) `(begin ,@(include/resolve (cdr obj)))]
           [else (imap replace-object obj)])]
        [else obj])))
  (define directory-separator-string
    (list->string `(,(directory-separator))))
  (define include/resolve
    (lambda (args)
      (let ([dir-args (car args)] [filename (cadr args)])
        (replace-source
          (apply
            join-string
            directory-separator-string
            (append (cdr dir-args) (list filename)))))))
  (define imap
    (lambda (proc ilist)
      (let loop ([i ilist])
        (cond
          [(null? i) i]
          [else
           (cons*
             (proc (car i))
             (cond
               [(list? (cdr i)) (loop (cdr i))]
               [else (proc (cdr i))]))]))))
  (define join-string
    (lambda (sep . str-parts)
      (cond
        [(null? str-parts) ""]
        [else
         (let loop ([acc (car str-parts)] [rest (cdr str-parts)])
           (cond
             [(null? rest) acc]
             [else
              (loop (string-append acc sep (car rest)) (cdr rest))]))]))))

